apiVersion: v1
stringData:
  imap.rc: |
    [retriever]
    type = SimpleIMAPSSLRetriever
    server = imap.gmail.com
    username = {{ .Values.imap.gmail.username }}
    password = {{ .Values.imap.gmail.password }}
    mailboxes = {{ .Values.imap.gmail.mailboxes }}
    [destination]
    type = MDA_external
    path = /scripts/process-emails
    allow_root_commands = true
    [options]
    read_all = false
    delete_after = 1
    delivered_to = false
    received = false
    message_log_syslog = true
    message_log_verbose = true
kind: Secret
metadata:
  name: '{{ .Chart.Name }}-getmail-secrets'
  annotations:
    secret.jenkins-x.io/prefix: {{ .Values.prefix }}
type: Opaque
